name: Compilability check
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        abi: [ "armeabi-v8a", "arm64-v7a" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4   # 修正版本

      - name: Setup the environment
        run: |
          sudo apt update
          sudo apt install meson nasm ninja-build -y

      - name: Enable MediaCodec and JNI support
        run: |
          # 在 build.sh 中的 FFMPEG_CONFIG_ARGS 末尾追加硬解参数
          sed -i '/FFMPEG_CONFIG_ARGS=/ s/$/ --enable-jni --enable-mediacodec/' scripts/ffmpeg/build.sh

      - name: Executing the script
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./ffmpeg-android-maker.sh -all-free -all-gpl -mbedtls -android=24 -abis=${{ matrix.abi }}

      - name: Force static linking and disable shared libs
        run: |
          # 修改 build.sh，在 FFMPEG_CONFIG_ARGS 中追加静态链接参数
          sed -i '/FFMPEG_CONFIG_ARGS=/ s/$/ --disable-shared --enable-static --extra-ldflags="-static-libgcc -static-libstdc++"/' scripts/ffmpeg/build.sh
          # 同时确保 --disable-shared 在脚本里已经存在，如果没有，这个追加会生效

      - name: Upload binaries (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.abi }}
          path: build
